<<<<<<< HEAD
name: 'walmart_dbt'
version: '1.0.0'
profile: 'walmart_dbt'

=======

# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'walmart_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'walmart_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
>>>>>>> 7993812 (Primer commit del proyecto walmart_dbt)
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

<<<<<<< HEAD
clean-targets:
  - "target"
  - "dbt_packages"

=======
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
>>>>>>> 7993812 (Primer commit del proyecto walmart_dbt)
models:
  walmart_dbt:
    raw:
      +database: WALMART_RAW
      +schema: raw
    staging:
      +database: WALMART_STAGING
      +schema: staging
      +materialized: table
    master:
      +database: WALMART_MASTER
      +schema: master
      +materialized: table

seeds:
  walmart_dbt:
<<<<<<< HEAD
    +schema: raw
    raw_walmart_data:
      +delimiter: ";"
=======
    +schema: raw  # Esquema de la base de datos
    raw_walmart_data:
      +delimiter: ";"  # El delimitador de las columnas en los archivos CSV (punto y coma)
>>>>>>> 7993812 (Primer commit del proyecto walmart_dbt)
      +column_types:
        customer_id: int
        age: int
        gender: varchar(10)
        income_bracket: varchar(10)
        loyalty_program: varchar(3)
        membership_years: int
        churned: varchar(3)
        marital_status: varchar(10)
        number_of_children: int
        education_level: varchar(20)
        occupation: varchar(20)
        transaction_id: int
        transaction_date: varchar(20)
        product_id: int
        product_category: varchar(50)
        quantity: int
        unit_price: float
        discount_applied: float
        payment_method: varchar(20)
        store_location: varchar(20)
        transaction_hour: int
        day_of_week: varchar(10)
        week_of_year: int
        month_of_year: int
        avg_purchase: float
        purchase_frequency: varchar(10)
        last_purchase_date: varchar(20)
        avg_discount: float
        preferred_store: varchar(20)
        online_purchases: int
        in_store_purchases: int
        avg_items_per_transaction: float
<<<<<<< HEAD
        avg_transacion_value: float
=======
        avg_transaction_value: float
>>>>>>> 7993812 (Primer commit del proyecto walmart_dbt)
        total_returned_items: int
        total_returned_value: float
        total_sales: float
        total_transactions: int
        total_items_purchases: int
        total_discounts_received: float
        avg_spent_per_category: float
        max_single_purchase_value: float
        min_single_purchase_value: float
        product_name: varchar(50)
        product_brand: varchar(50)
        product_rating: float
        product_review_count: int
        product_stock: int
        product_return_rate: float
        product_size: varchar(10)
        product_weight: float
        product_color: varchar(20)
        product_material: varchar(20)
        product_manufacture_date: varchar(20)
        product_expiry_date: varchar(20)
        product_shelf_life: int
        promotion_id: int
        promotion_type: varchar(20)
        promotion_start_date: varchar(20)
        promotion_end_date: varchar(20)
        promotion_effectiveness: varchar(10)
        promotion_channel: varchar(20)
        promotion_target_audience: varchar(30)
        customer_zip_code: varchar(10)
        customer_city: varchar(20)
        customer_state: varchar(20)
        store_zip_code: varchar(10)
        store_city: varchar(20)
        store_state: varchar(20)
        distance_to_store: float
        holiday_season: varchar(3)
        season: varchar(10)
        weekend: varchar(3)
        customer_support_calls: int
        email_subscriptions: varchar(3)
        app_usage: varchar(10)
        website_visits: int
        social_media_engagement: varchar(10)
<<<<<<< HEAD
        days_since_last_purchase: int
=======
        days_since_last_purchase: int
>>>>>>> 7993812 (Primer commit del proyecto walmart_dbt)
