name: Run DBT on Push

on:
  push:
    branches:
      - main
      - '**'
jobs:
  dbt-job:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Instalar ODBC Driver 17 for SQL Server
        run: |
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y curl gnupg unixodbc-dev
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install dbt-sqlserver
          
      - name: Obtener IP del runner
        run: |
          RUNNER_IP=$(curl -s https://api.ipify.org)
          echo "RUNNER_IP=$RUNNER_IP" >> $GITHUB_ENV
          echo "Runner IP: $RUNNER_IP"
      - name: Login en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Agregar IP a la lista de IPs validos
        run: |
          az sql server firewall-rule create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --server ${{ secrets.AZURE_SERVER_NAME }} \
            --name AllowGitHubActionsIP \
            --start-ip-address ${{ env.RUNNER_IP }} \
            --end-ip-address ${{ env.RUNNER_IP }}

      - name: Crear archivo profiles.yml desde secret
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES }}" > ~/.dbt/profiles.yml

      - name: Instalar paquetes de DBT
        run: dbt deps

      - name: Ejecutar dbt para todos los targets
        run: |
          dbt debug --target raw
          dbt debug --target staging
          dbt debug --target master

      - name: Ejecutar dbt run
        run: dbt run

      - name: Ejecutar dbt test
        run: dbt test

      - name: Quitar el IP de la lista de IPs validos
        if: always()
        run: |
          az sql server firewall-rule delete \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --server ${{ secrets.AZURE_SERVER_NAME }} \
            --name AllowGitHubActionsIP